zoom: 15,
styles:
[
	{
		"elementType": "labels.icon",
		"stylers":
		[
			{"invert_lightness": true},
			{"hue": "#ffdd00"},
			{"lightness": -22},
			{"saturation": -42},
			{"visibility": "off"}
		]
	},
	{
		"featureType": "administrative.neighborhood",
		"elementType": "labels",
		"stylers": [{"visibility": "off"}]
	},
	{
		"featureType": "administrative",
		"elementType": "geometry",
		"stylers": [{"visibility": "off"}]
	},
	{
		"featureType": "administrative.country",
		"elementType": "labels",
		"stylers": [{"visibility": "off"}]
	},
	{
		"featureType": "administrative.province",
		"elementType": "labels",
		"stylers": [{"visibility": "off"}]
	},
	{
		"featureType": "water",
		"elementType": "geometry",
		"stylers":
		[
			{"saturation": -38},
			{"lightness": -54},
			{"hue": "#00e5ff"}
		]
	},
	{
		"featureType": "water",
		"elementType": "labels.text.fill",
		"stylers":
		[
			{"color": "#ffffff"},
			{"saturation": 54},
			{"lightness": 51},
			{"visibility": "on"}
		]
	},
	{
		"featureType": "water",
		"elementType": "labels.text.stroke",
		"stylers": [{"visibility": "off"}]
	}
],
mapTypeId: google.maps.MapTypeId.ROADMAP